### ISSUE TITLE
Error with msg.payload as JSON

### ISSUE THREAD

**Issue by JK40105** [dceejay/node-red-contrib-zeromq#3]
Since version 0.0.8 if specifying zeromq node output as "a JSON object if possible" the error "failed to parse" is issued if msg.payload really is a JSON object.
I think the test(s):
   if (node.output !== "buffer") {        --> e.g at line 46
have to be changed to:
   if (node.output !== "buffer" && node.output !== "json") {
otherwise JSON output is handled twice as string and as json (but I am not so experienced with javascript, so please discard this comment if I am wrong)

**Comment by dceejay** [comment]
Not sure what is going on.  It needs to be handled twice as it first needs to convert the buffer to a string whether it is json or not... and then try to parse that string.

**Comment by dceejay** [comment]
Ah - right yes Ok - see the problem - if you send a msg with something like a simple topic that is a string then that part will fail... so I need to handle that better.

Actually they can probably just suppressed for now... pushed as version 0.0.9

**Comment by JK40105** [comment]
Dear Mr. Conway,

 

I ran your flow and got these messages:

 

3/15/2021, 12:06:36 PMnode: 4e8c3e40.b0a9msg : string[15]

"Failed to parse"

3/15/2021, 12:06:36 PMnode: 2e94a45d.b48d4ctest : msg : Object

object

topic: "test"

error: true

payload: object

a: "A"

b: "B"

_msgid: "e8271901.459838"

 

I had installed version 0.0.7 via npm and updated to 0.0.8 via “Manage palette”, maybe this has an influence.

This is the export of my flow:

[{"id":"3eac349d.93b8dc","type":"inject","z":"7f7c6824.54e94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test","payload":"{\"a\":\"A\", \"b\":\"B\" }","payloadType":"json","x":150,"y":760,"wires":[["3e490048.5051f"]]},{"id":"3e490048.5051f","type":"zeromq out","z":"7f7c6824.54e94","name":"","topic":"test","fields":"topic,payload","server":"tcp://127.0.0.1:5556","isserver":true,"intype":"pub","x":350,"y":760,"wires":[]},{"id":"4e8c3e40.b0a9","type":"zeromq in","z":"7f7c6824.54e94","name":"","topic":"test","fields":"topic,payload","server":"tcp://127.0.0.1:5556","output":"json","isserver":false,"intype":"sub","x":130,"y":820,"wires":[["2e94a45d.b48d4c"]]},{"id":"2e94a45d.b48d4c","type":"debug","z":"7f7c6824.54e94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":350,"y":820,"wires":[]}]

 

Yours sincerely,

Hannes Kiesbauer

**Comment by JK40105** [comment]
Sorry, I made a mistake: I installed version 0.0.6 via npm, not 0.0.7, and updated to 0.0.8 via manage palette

 

From: IT-Beratung ***@***.***> 
Sent: Montag, 15. März 2021 12:24
To: 'dceejay/node-red-contrib-zeromq' ***@***.***>
Subject: RE: [dceejay/node-red-contrib-zeromq] Error with msg.payload as JSON (#3)

 

Dear Mr. Conway,

 

I ran your flow and got these messages:

 

3/15/2021, 12:06:36 PMnode: 4e8c3e40.b0a9msg : string[15]

"Failed to parse"

3/15/2021, 12:06:36 PMnode: 2e94a45d.b48d4ctest : msg : Object

object

topic: "test"

error: true

payload: object

a: "A"

b: "B"

_msgid: "e8271901.459838"

 

I had installed version 0.0.7 via npm and updated to 0.0.8 via “Manage palette”, maybe this has an influence.

This is the export of my flow:

[{"id":"3eac349d.93b8dc","type":"inject","z":"7f7c6824.54e94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test","payload":"{\"a\":\"A\", \"b\":\"B\" }","payloadType":"json","x":150,"y":760,"wires":[["3e490048.5051f"]]},{"id":"3e490048.5051f","type":"zeromq out","z":"7f7c6824.54e94","name":"","topic":"test","fields":"topic,payload","server":"tcp://127.0.0.1:5556","isserver":true,"intype":"pub","x":350,"y":760,"wires":[]},{"id":"4e8c3e40.b0a9","type":"zeromq in","z":"7f7c6824.54e94","name":"","topic":"test","fields":"topic,payload","server":"tcp://127.0.0.1:5556","output":"json","isserver":false,"intype":"sub","x":130,"y":820,"wires":[["2e94a45d.b48d4c"]]},{"id":"2e94a45d.b48d4c","type":"debug","z":"7f7c6824.54e94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":350,"y":820,"wires":[]}]

 

Yours sincerely,

Hannes Kiesbauer

**Comment by JK40105** [comment]
Dear Mr. Conway,

 

I have another question:

If I add another msg object, e.g. msg.command to the comma-separated “Fields” list, this field is disappeared when I open the zeromq node the next time, e.g. for changing the port, and I am not really sure if it got observed the first time.

What is the correct way to add such an additional msg object?

 

Thanks for your help.

Hannes Kiesbauer

**Comment by JK40105** [comment]
Yes, output «String if possible” is handled OK.

**Comment by dceejay** [comment]
Yes - there was an issue with setting (or rather retaining) the fields... fixed in 0.0.10
