### ISSUE TITLE
 Error: Cannot find module 'rimraf'

### ISSUE THREAD

**Issue by aaffany** [dceejay/node-red-contrib-zeromq#4]
Hello, i have an issue with installing node-red-contrib-zeromq . I tried to install it from palette and i show me that : 
"
> zeromq@5.2.8 install /usr/lib/node_modules/node-red/node_modules/node-red-contrib-zeromq/node_modules/zeromq
> node-gyp-build || npm run build:libzmq

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'rimraf'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:489:15)
gyp ERR! stack     at Function.Module._load (module.js:439:25)
gyp ERR! stack     at Module.require (module.js:517:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-red/node_modules/node-gyp/lib/clean.js:10:10)
gyp ERR! stack     at Module._compile (module.js:573:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:584:10)
gyp ERR! stack     at Module.load (module.js:507:32)
gyp ERR! stack     at tryModuleLoad (module.js:470:12)
gyp ERR! stack     at Function.Module._load (module.js:462:3)
gyp ERR! System Linux 4.14.9-klk
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-red/node_m... "

thnx for answering :)

**Comment by dceejay** [comment]
any clues like which version of nodejs, npm, Node-RED , platform, OS, etc ?

**Comment by aaffany** [comment]
I m implementing this api in a  gateway using : nodejs (version v8.4.0) , nodered (verion v0.18.1), npm (version 5.3.0) in an OS named Keros (kind of linux distibution " Linux 4.14.9-klk arm LE")

**Comment by dceejay** [comment]
node 8 went out of support a while back. I guess you could try manually installing the rimraf package to your ~/.node-red directory and then re-installing.

**Comment by aaffany** [comment]
Thanks for the support :)
