### ISSUE TITLE
NodeRed Dumping after installation

### ISSUE THREAD

**Issue by biohazardxxx** [dceejay/node-red-contrib-zeromq#6]
Hi, after installin gthis node to my dockered NodeRed it was crashing and not able to start again:

> 2023-11-30T15:09:10.852902554Z Welcome to Node-RED
> 2023-11-30T15:09:10.852906462Z ===================
> 2023-11-30T15:09:10.852909968Z 
> 2023-11-30T15:09:10.853793660Z 30 Nov 16:09:10 - [info] Node-RED version: v3.0.2
> 2023-11-30T15:09:10.854090694Z 30 Nov 16:09:10 - [info] Node.js  version: v16.16.0
> 2023-11-30T15:09:10.854210401Z 30 Nov 16:09:10 - [info] Linux 5.15.39-4-pve x64 LE
> 2023-11-30T15:09:11.298004494Z 30 Nov 16:09:11 - [info] Loading palette nodes
> 2023-11-30T15:09:13.025626938Z ./entrypoint.sh: line 14:     8 Segmentation fault      (core dumped) /usr/local/bin/node $NODEOPTIONS node_modules/node-red/red.js --userDir /data $FLOWS

Would you have any hint please?

**Comment by biohazardxxx** [comment]
Saw there is #5 but same happens when running latest nodered.

> Welcome to Node-RED
> ===================
> 
> 30 Nov 16:27:01 - [info] Node-RED version: v3.1.0
> 30 Nov 16:27:01 - [info] Node.js  version: v16.20.2
> 30 Nov 16:27:01 - [info] Linux 5.15.39-4-pve x64 LE
> 30 Nov 16:27:02 - [info] Loading palette nodes
> ./entrypoint.sh: line 14:     8 Segmentation fault      (core dumped) /usr/local/bin/node $NODE_OPTIONS node_modules/node-red/red.js --userDir /data $FLOWS "${@}"

**Comment by dceejay** [comment]
Just guessing at this point - but I know the zeromq node has a large binary component so will need to rebuild when installed... the default docker images are Alpine based and not Debian so they may not automatically build. You may need to use the debian based container instead ?

**Comment by biohazardxxx** [comment]
Thanks @dceejay! Have started the container up with nodered/node-red:latest-debian image and it starts up fine again.
